In [1]:
import numpy as np

In [8]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [13]:
l = [[1,2,3],[2,4,5],[2,4,5]]
l

[[1, 2, 3], [2, 4, 5], [2, 4, 5]]

In [18]:
np.array(l)#this is how we creta an 2 dimentional array

array([[1, 2, 3],
       [2, 4, 5],
       [2, 4, 5]])

In [17]:
arr=np.arange(1,11)#this is how we create an array of 1 to target
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr=np.zeros(6)# this is how we can create zeros in array
arr

array([0., 0., 0., 0., 0., 0.])

In [21]:
arr=np.zeros((6,6)) # this is how we can create matrix 
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
arr=np.ones((2,2))# this is we can print differnt numbers matrix using tags
arr

array([[1., 1.],
       [1., 1.]])

In [27]:
arr=np.linspace(1,5,5)# this is for creating space
arr

array([1., 2., 3., 4., 5.])

In [28]:
arr=np.random.rand(10) #using this rand you will get the random varibale between 0 to1
arr

array([0.6130374 , 0.40878699, 0.76920502, 0.09328429, 0.17552364,
       0.51140471, 0.96613663, 0.69733885, 0.79939526, 0.97379688])

In [29]:
arr=np.random.randn(10)
arr

array([-1.8901883 ,  0.74888756, -1.19503691,  0.2416146 ,  0.953649  ,
        0.44407427,  1.80456417,  1.45163899, -1.30144498, -0.92650524])

In [31]:
arr=np.random.randint(6) #this function will generate int between 0 to 6
arr

4

In [33]:
arr=np.random.randint(10,20,10)#this will helo to generate mutiple numbers
arr

array([12, 14, 15, 17, 17, 11, 13, 17, 12, 14], dtype=int32)