In [7]:
import numpy as np

In [9]:
arr=np.array([[1,2,3,43,4],[2,3,4,5,56]])
arr

array([[ 1,  2,  3, 43,  4],
       [ 2,  3,  4,  5, 56]])

In [11]:
l=[[1,2,3,4],[2,3,4,5]]
l

[[1, 2, 3, 4], [2, 3, 4, 5]]

In [12]:
arr=np.array(l)
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [15]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
a=np.linspace(1,20,5)
a

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [22]:
a=np.random.randint(100)
a

48

In [24]:
arr=np.array([[1,2,3,4],[2,3,4,5]])
arr

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [25]:
arr.shape

(2, 4)

In [27]:
arr.size

8

In [28]:
arr.dtype

dtype('int64')

In [30]:
arr.max()

np.int64(5)

In [31]:
arr.min()

np.int64(1)

In [33]:
arr.mean()

np.float64(3.0)

In [35]:
arr.sum()

np.int64(24)

In [39]:
np.sum(arr,axis=1)

array([10, 14])

In [40]:
np.sum(arr,axis=0)

array([3, 5, 7, 9])

In [41]:
arr.std()

np.float64(1.224744871391589)

In [42]:
arr.argmax()

np.int64(7)

In [43]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
arr=arr.reshape(4,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [66]:
arr[:,0]

array([ 1,  6, 11, 16])

In [69]:
arr[0,:]

array([1, 2, 3, 4, 5])

In [70]:
a1=np.array([1,2,3,4])
a2=np.array([2,3,4,5])

a1+a2

array([3, 5, 7, 9])

In [72]:
arr=np.array([[1,2,3,4],[3,4,5,6]])
arr

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [74]:
for i in range(len(arr)):
    print(arr[i])

[1 2 3 4]
[3 4 5 6]


In [1]:
import numpy as np


In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [11]:
array=np.zeros(12)
array


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
array.reshape((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.size(array)

12

In [14]:
np.shape(array)

(12,)

In [15]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [16]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
second_coloum=arr[:,1]
print(second_coloum)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [3]:
import numpy as np

In [4]:
arr= np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [17]:
arr*3

array([ 30,  60,  90, 120, 150])

In [21]:
arr=np.random.randint(1,101,(4,4))
arr

array([[28, 70, 38, 81],
       [49, 57, 16, 60],
       [53, 37, 70, 98],
       [64, 98,  2, 67]], dtype=int32)

In [22]:
arr.max()

np.int32(98)

In [23]:
arr.min()

np.int32(2)

In [24]:
arr.min()

np.int32(2)

In [25]:
arr1=np.random.randint(1,11,(2,3))
arr1

array([[7, 5, 6],
       [8, 8, 3]], dtype=int32)

In [27]:
arr2=np.random.randint(11,21,(2,3))
arr2

array([[12, 16, 19],
       [13, 11, 20]], dtype=int32)

In [29]:
verucally=np.vstack((arr1,arr2))
verucally

array([[ 7,  5,  6],
       [ 8,  8,  3],
       [12, 16, 19],
       [13, 11, 20]], dtype=int32)

In [30]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
auu=arr.reshape(3,4)
auu


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
luu=auu.transpose()
luu

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [39]:
flo=np.random.rand(5,5)
flo

array([[0.49466539, 0.93807285, 0.42532325, 0.94408326, 0.91354904],
       [0.92863604, 0.78722733, 0.84593881, 0.430096  , 0.17910058],
       [0.50571748, 0.39742698, 0.19982903, 0.95304301, 0.72559756],
       [0.01872772, 0.91125927, 0.07408471, 0.77423438, 0.75125351],
       [0.88743886, 0.89149911, 0.47273639, 0.41902101, 0.69898285]])

In [41]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
b = np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [44]:
mul=a*b
mul

array([[ 7, 16, 27],
       [40, 55, 72]])

In [46]:
mul

array([[ 7, 16, 27],
       [40, 55, 72]])

In [48]:
mul.shape

(2, 3)