In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
l=[[1,2,3,4],[1,2,3,4]]
l

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [6]:
np.array(l)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr=np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr=np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
arr=np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [21]:
arr=np.random.randint(10)
arr

5

In [3]:
arr=np.array([[1,2,3],[3,2,3],[2,3,4]])
arr

NameError: name 'np' is not defined

In [2]:
arr.shape # this is for knowing how many rows are there inside a array line rows & colm

NameError: name 'arr' is not defined

In [26]:
arr.size # this is for knowing many many int is there inside an array

6

In [27]:
arr.dtype # this is to know how the deta type 

dtype('int64')

In [28]:
arr.min() # this is to know the mini mum numbers present in side an array

np.int64(1)

In [31]:
arr.max() # this is to know know the maximum number present inside an array

np.int64(3)

In [32]:
arr.sum() # this is how we can get the total sum of an array

np.int64(12)

In [39]:
np.sum(arr,axis=1)# this will do the addition of the colloms and if you want the sum of the rows the 1

array([6, 8, 9])

In [41]:
np.sum(arr,axis=0)

array([ 6,  7, 10])

In [43]:
arr.mean() # this is to take out the mean

np.float64(2.5555555555555554)

In [44]:
arr.std() # this is to take out the standers daviation

np.float64(0.8314794192830981)

In [45]:
arr.argmax() # this is to take out thre maximun numbers index number

np.int64(8)

In [46]:
arr.argmin() #this is to take out thre minimum numbers index number

np.int64(0)

In [ ]:
RESHAPING AND RE SIZING

In [51]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr=arr.reshape(6,5)# to reshape we need to do the calcution that we need to fit all the elemts, so foe thet we need to have the idea of taking in how many rows and collms the elemsts will fit.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
ARRAY OPERATIONS


In [2]:
import numpy as np

In [3]:
a1= np.array([1,2,3,4])
a2= np.array([5,6,7,8])
a2

array([5, 6, 7, 8])

In [4]:
a1 + a2 # this is how we can add 2 arrays

array([ 6,  8, 10, 12])

In [15]:
a1-a2 # ths i for minous

array([-4, -4, -4, -4])

In [16]:
a1*a2 # this is for mutiplicatons

array([ 5, 12, 21, 32])

In [17]:
a1/a2 # thia is how you can convert to bullian

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [18]:
a1//a2 # this is float divition

array([0, 0, 0, 0])

In [19]:
a1 **a2 #we can aslo add the power 

array([    1,    64,  2187, 65536])

In [ ]:
BROADCASTING 

In [23]:
l=[10,20,30,40,50] # this is how we can create an array
arr=np.array(l)

In [24]:
for i in l:    # this is for loop 
    print(i+10)

20
30
40
50
60


In [ ]:
#if you dont want to use the for loop you can do 

In [25]:
arr +10 # this is hpw you can aslo perfom

array([20, 30, 40, 50, 60])

In [29]:
arr2= np.arange(1,26).reshape(5,5) # this how you can add any numbers in your matrix


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
DEEP AND SHALLOW COPY

In [36]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
slice=a[:4] # thia ia how you can do the slice of a numbers 
slice


array([1, 2, 3, 4])

In [45]:
slice=slice*10 #thi is how you can multiply 
slice

array([10, 20, 30, 40])

In [ ]:
#you canot chmage nay thything inside an array but you can change inside an list

In [55]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [56]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [57]:
a@b #this is how you can do the multiplication of matrix

array([[19, 22],
       [43, 50]])

In [58]:
a.T # thia ia how you can do the transpose og an matrix

array([[1, 3],
       [2, 4]])

In [5]:
import numpy as np

In [20]:
a=np.array([[1,2,3,4],[3,4,5,6],[1,2,3,4],[1,2,3,4]])
a

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [23]:
arr=np.hsplit(a,2) #thia is for spliting an array in horizentally
arr

[array([[1, 2],
        [3, 4],
        [1, 2],
        [1, 2]]),
 array([[3, 4],
        [5, 6],
        [3, 4],
        [3, 4]])]

In [25]:
arr=np.vsplit(a,2) #this is how you can split array in vertically
arr

[array([[1, 2, 3, 4],
        [3, 4, 5, 6]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [28]:
for i in a:
    print(i)

[1 2 3 4]
[3 4 5 6]
[1 2 3 4]
[1 2 3 4]


In [5]:
import numpy as np

In [6]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [18]:
b=np.sum(s,axis=1) 
# [b==45]
for i in b:
    if i != 45:
        print("Suduko is not for rowes valid")
        break
else:
    print("sudoko is valid")

sudoko is valid


In [22]:
c=np.sum(b,axis=0)
for i in b:
    if i !=45:
        print("Sudoko is not colums valid")
        break
else:
    print("Sudoko is valid")
    

Sudoko is valid


In [27]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [28]:
s[0:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])