In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
l=[[1,2,3,4],[1,2,3,4]]
l

[[1, 2, 3, 4], [1, 2, 3, 4]]

In [6]:
np.array(l)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [7]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr=np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr=np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
arr=np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [21]:
arr=np.random.randint(10)
arr

5

In [37]:
arr=np.array([[1,2,3],[3,2,3],[2,3,4]])
arr

array([[1, 2, 3],
       [3, 2, 3],
       [2, 3, 4]])

In [25]:
arr.shape # this is for knowing how many rows are there inside a array line rows & colm

(2, 3)

In [26]:
arr.size # this is for knowing many many int is there inside an array

6

In [27]:
arr.dtype # this is to know how the deta type 

dtype('int64')

In [28]:
arr.min() # this is to know the mini mum numbers present in side an array

np.int64(1)

In [31]:
arr.max() # this is to know know the maximum number present inside an array

np.int64(3)

In [32]:
arr.sum() # this is how we can get the total sum of an array

np.int64(12)

In [39]:
np.sum(arr,axis=1)# this will do the addition of the colloms and if you want the sum of the rows the 1

array([6, 8, 9])

In [41]:
np.sum(arr,axis=0)

array([ 6,  7, 10])

In [43]:
arr.mean() # this is to take out the mean

np.float64(2.5555555555555554)

In [44]:
arr.std() # this is to take out the standers daviation

np.float64(0.8314794192830981)

In [45]:
arr.argmax() # this is to take out thre maximun numbers index number

np.int64(8)

In [46]:
arr.argmin() #this is to take out thre minimum numbers index number

np.int64(0)

In [ ]:
RESHAPING AND RE SIZING

In [51]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr=arr.reshape(6,5)# to reshape we need to do the calcution that we need to fit all the elemts, so foe thet we need to have the idea of taking in how many rows and collms the elemsts will fit.
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])